### ISSUE TITLE
vspkdoc consistency with v5_0 

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vspkdoc#3]
Hi all,
with v5_0 release I see that URL for html docs has been changed:
`https://nuagenetworks.github.io/vspkdoc/html/v4_0/nuaddressrange.html` (old)
`https://nuagenetworks.github.io/vspkdoc/v4_0/nuaddressrange.html` (new)
Was it an intended change? 

Moreover, I see that all objects in v4_0 endpoint were updated as v5_0. 
The question boils down to `how to browse v4_0 vspk docs`?

**Comment by pdellaert** [comment]
@little-dude is there a way we can expose both 4_0 and 5_0 as we do with the vsd-api-documentation?

**Comment by little-dude** [comment]
> Was it an intended change?

That was accidental but I actually liked it better so I kept it. Is that a problem?

> I see that all objects in v4_0 endpoint were updated as v5_0

We have two major version of VSPK now:

- 5.0.x.y versions have `v5_0` and `v4_0`.
- 4.0.x.y versions have `v4_0` and `v3_2`.

> The question boils down to how to browse v4_0 vspk docs?

It is available right now, if you scroll down far enough on the left pane. Or am I missing something?

**Comment by hellt** [comment]
>That was accidental but I actually liked it better so I kept it. Is that a problem?

We (EMEA NPI) can change all the links to vspk objs we placed in the many docstrings. Just wanted to do this once (that is why I wanted to check that it was a change that will stay)

> if you scroll down far enough on the left pane

My bad, that was unexpected to me =)

Thanks for comments @little-dude, I am closing this one now.
